// quiz/src/components/ConteudoForm/ConteudoForm.tsx
import {FormEvent, useState} from "react";
import {inRange, isInt, required} from "../../utils/validation";
import {IConteudo} from "../../models/IConteudo";
import {useErrors} from "../../hooks/error-hook";
import {useTouch} from "../../hooks/touched-hook";
import "./ConteudoForm.css"


interface IConteudoForm {
    onSubmit: (conteudos: IConteudo[]) => void
}

export function ConteudoForm({ onSubmit }: IConteudoForm) {
    const [ conteudos, setConteudos ] = useState<IConteudo[]>([{
        conteudo: "",
        titulo: ""
    } as IConteudo])
    const { errors, setErrors, check } = useErrors<{[name: string]: boolean}>()     // erros nos campos dos formulários
    const { touched, touch } = useTouch()  // indica, para cada campo, se ele foi alterado pelo usuário


    /**
     * Altera o número de conteudos.
     * @param value Novo número de opções
     */
    function mudarNumConteudo(value: string) {
        // cria uma função de validação cujo valor deve estar entre 1 e 5
        const range = inRange(1, 5)

        // função de validação combina outras funções de validação
        // o erro atribuído será o da primeira que retornar algum erro, devido ao "ou" (||)
        const validateFunc = (value: string) => required(value) || isInt(value) || range(value)

        // se passar no teste de validação, altera o tamanho do array `options`
        if (check(value, validateFunc, 'numConteudo')) {
            const qtdRequisitada = parseInt(value, 10)
            if (qtdRequisitada <= conteudos.length) {
                for (let i = qtdRequisitada; i < conteudos.length; i++) {
                    touch(`conteudo_aba_titulo_${i}`, false) // limpa os indicadores de alteraçao dos conteudos removidos
                    touch(`conteudo_aba_conteudo_${i}`, false) // limpa os indicadores de alteraçao dos conteudos removidos
                    setErrors(`conteudo_aba_titulo_${i}`, '') // limpa as mensagens de erro dos conteudos removidos
                    setErrors(`conteudo_aba_conteudo_${i}`, '') // limpa as mensagens de erro dos conteudos removidos
                }
                setConteudos(conteudos.slice(0, qtdRequisitada))

            }
            else {
                const novosConteudos = [...conteudos]
                while (novosConteudos.length < qtdRequisitada) {
                    novosConteudos.push({
                        conteudo: '',
                        titulo: ''
                    } as IConteudo)
                }
                setConteudos([...novosConteudos])

            }
        }
    }

    function mudarTituloAba(index: number, value: string) {
        const novoConteudo = [...conteudos]
        novoConteudo[index].titulo = value
        setConteudos(novoConteudo)
        touch(`conteudo_aba_titulo_${index}`)
    }

    function mudarConteudoAba(index: number, value: string) {
        const novoConteudo = [...conteudos]
        novoConteudo[index].conteudo = value
        setConteudos(novoConteudo)
        touch(`conteudo_aba_conteudo_${index}`)
    }

    /**
     * Verifica se há erros no formulário e, se estiverem corretos, trata os dados.
     * @param e Evento de submissão do formulário
     */
    function submit(e: FormEvent) {
        e.preventDefault()
        conteudos.forEach( (conteudo, index) => {
            check(conteudo.conteudo, required, `conteudo_aba_conteudo_${index}`)
            check(conteudo.titulo, required, `conteudo_aba_titulo_${index}`)
        })

        const optionsOk = conteudos
                .map( ( conteudo, index ) =>
                    check(conteudo.conteudo, required, `conteudo_aba_conteudo_${index}`)
                    && check(conteudo.titulo, required, `conteudo_aba_titulo_${index}`) )
                .every(obj => obj)

        if (optionsOk) {
            onSubmit( conteudos )
        }
    }

    // Elemento com o número de opções
    const numAbasElm = (
        <div>
            <label>Num. Tabs</label>
            <input type="number" value={conteudos.length} onChange={e => mudarNumConteudo(e.target.value)} />
            <div className="error">{ errors.numConteudo }</div>
        </div>
    )

    // Lista com as opções
    const listaConteudosElm = conteudos.map((conteudo, index) => (
        <div key={`conteudo_aba_${index}`}>
            <label>Título</label>
            <input type="text" value={conteudo.titulo}
                   id={`conteudo_aba_titulo_${index}`}
                   key={`conteudo_aba_titulo_${index}`}
                   onChange={e => mudarTituloAba(index, e.target.value)}
                   onBlur={e => touched[`conteudo_aba_titulo_${index}`] && check(e.target.value, required, `conteudo_aba_titulo_${index}`)}
            />
            <div className="error">{ errors[`conteudo_aba_titulo_${index}`] }</div>
            <label>Conteúdo</label>
            <textarea value={conteudo.conteudo}
                      key={`conteudo_aba_conteudo_${index}`}
                      id={`conteudo_aba_conteudo_${index}`}
                      onChange={e => mudarConteudoAba(index, e.target.value)}
                      onBlur={e => touched[`conteudo_aba_conteudo_${index}`] && check(e.target.value, required, `conteudo_aba_conteudo_${index}`)}
            >
            </textarea>
            <div className="error">{ errors[`conteudo_aba_conteudo_${index}`] }</div>
        </div>
    ))

    const botoes = (
        <div>
            <div className="buttons">
                <input type="submit" value="Enviar" />
            </div>
        </div>
    )

    // Formulário completo
    return (
        <form className="qst-form" onSubmit={submit}>
            { numAbasElm }
            { listaConteudosElm }
            { botoes }
        </form>
    )
}

// quiz/src/components/ConteudoForm/ConteudoForm.vue
<template>
  <form class="qst-form" @submit.prevent="submit">
    <div>
      <label>Num. Tabs</label>
      <input type="number"
             :value="conteudos.length"
             @change="mudarNumConteudo($event.target.value)" />
      <div class="error">{{ errorValidation.errors.numConteudo }}</div>
    </div>
    <div v-for="(conteudo, index) in conteudos"
         :key="`conteudo_aba_${index}`">
      <label>Título</label>
      <input type="text" v-model="conteudo.titulo"
             :key="`conteudo_aba_titulo_${index}`"
             @change="verificarTituloAba(index)"
             @blur="touchValidation.touched[`conteudo_aba_titulo_${index}`] && errorValidation.check($event.target.value, required, `conteudo_aba_titulo_${index}`)"
      />
      <div class="error">{{ errorValidation.errors[`conteudo_aba_titulo_${index}`] }}</div>
      <label>Conteúdo</label>
      <textarea v-model="conteudo.conteudo"
                :key="`conteudo_aba_conteudo_${index}`"
                @blue="touchValidation.touched[`conteudo_aba_conteudo_${index}`] && errorValidation.check($event.target.value, required, `conteudo_aba_conteudo_${index}`)"
                @change="verificarConteudoAba(index)"
      >
      </textarea>
      <div class="error">{{ errorValidation.errors[`conteudo_aba_conteudo_${index}`] }}</div>
    </div>
    <div>
      <div class="buttons">
        <input type="submit" value="Enviar" />
      </div>
    </div>
  </form>

</template>

<script setup lang="ts">
import type {ConteudoModel} from "@/models/CoteundoModel";
import {reactive} from "vue";
import { errorValidation } from "@/utils/errorValidation";
import { touchValidation} from "@/utils/touchValidation";
import {inRange, isInt, required} from "@/utils/validation";

export interface ConteudoFormEvent {
  (e: 'onSubmit', conteudos: ConteudoModel[]): void
}

const emit = defineEmits<ConteudoFormEvent>()
const conteudos = reactive<ConteudoModel[]>([{
  conteudo: "",
  titulo: ""
} as ConteudoModel])

/**
 * Altera o número de conteudos.
 * @param value Novo número de opções
 */
function mudarNumConteudo(value: string) {
  // cria uma função de validação cujo valor deve estar entre 1 e 5
  const range = inRange(1, 5)

  // função de validação combina outras funções de validação
  // o erro atribuído será o da primeira que retornar algum erro, devido ao "ou" (||)
  const validateFunc = (value: string) => required(value) || isInt(value) || range(value)

  // se passar no teste de validação, altera o tamanho do array `options`
  if (errorValidation.check(value, validateFunc, 'numConteudo')) {
    const qtdRequisitada = parseInt(value, 10)
    if (qtdRequisitada <= conteudos.length) {
      for (let i = qtdRequisitada; i < conteudos.length; i++) {
        touchValidation.touch(`conteudo_aba_titulo_${i}`, false) // limpa os indicadores de alteraçao dos conteudos removidos
        touchValidation.touch(`conteudo_aba_conteudo_${i}`, false) // limpa os indicadores de alteraçao dos conteudos removidos
        errorValidation.setErrors(`conteudo_aba_titulo_${i}`, '') // limpa as mensagens de erro dos conteudos removidos
        errorValidation.setErrors(`conteudo_aba_conteudo_${i}`, '') // limpa as mensagens de erro dos conteudos removidos
      }

      conteudos.splice(qtdRequisitada, conteudos.length - qtdRequisitada)

    }
    else {
      while (conteudos.length < qtdRequisitada) {
        conteudos.push({
          conteudo: '',
          titulo: ''
        } as ConteudoModel)
      }
    }
  }
}

function verificarTituloAba(index: number) {
  touchValidation.touch(`conteudo_aba_titulo_${index}`, true)
}

function verificarConteudoAba(index: number) {
  touchValidation.touch(`conteudo_aba_conteudo_${index}`, true)
}

/**
 * Verifica se há erros no formulário e, se estiverem corretos, trata os dados.
 */
function submit() {
  const optionsOk = conteudos
      .map( ( conteudo, index ) =>
          errorValidation.check(conteudo.conteudo, required, `conteudo_aba_conteudo_${index}`)
          && errorValidation.check(conteudo.titulo, required, `conteudo_aba_titulo_${index}`) )
      .every(obj => obj)

  if (optionsOk) {
    console.log()
    emit('onSubmit', [...conteudos])
  } else {
    conteudos.forEach( (conteudo, index) => {
      errorValidation.check(conteudo.conteudo, required, `conteudo_aba_conteudo_${index}`)
      errorValidation.check(conteudo.titulo, required, `conteudo_aba_titulo_${index}`)
    })}
}


</script>

<style scoped>
@import "ConteudoForm.css";
</style>
