// quiz/src/app/components/main/main.component.ts
import {Component} from '@angular/core';

@Component({
  selector: 'app-main',
  templateUrl: './main.component.html',
  styleUrls: ['./main.component.css']
})
export class MainComponent {
  conteudos = [{
    titulo: "Tab 1",
    conteudo: "Conteudo 1"
  }, {
    titulo: "Tab 2",
    conteudo: "Conteudo 2"
  }]
  abaSelecionada: number = 0


  constructor() {}

  select(optionIndex: number) {
    this.abaSelecionada = optionIndex
  }

}

<div id = "main">
  <app-conteudo-form></app-conteudo-form>
  <app-menu (selecao)="select($event)" [conteudos]="conteudos"></app-menu>
  <app-painel [conteudo]="conteudos[abaSelecionada].conteudo"> </app-painel>
</div>

// quiz/src/components/Main/main.svelte
<div>
    <div id = "main">
        <Menu on:selection={event => select(event.detail)}
              conteudos={ conteudos }
              selecionado={ abaSelecionada }
        ></Menu>
        <Painel conteudo={conteudos[abaSelecionada] ?
    conteudos[abaSelecionada].conteudo : ''}> </Painel>
    </div>
</div>

<script lang="ts">
    import Menu from '../Menu/menu.svelte'
    import Painel from '../Painel/painel.svelte'

    export const conteudos = [{
        titulo: 'Tab 1',
        conteudo: 'Conteudo 1'
    }, {
        titulo: 'Tab 2',
        conteudo: 'Conteudo 2'
    }]
    let abaSelecionada = 0
    function select(optionIndex: number) {
        abaSelecionada = optionIndex
    }
</script>

<style>
    #main {
        background-color: aliceblue;
    }
</style>
