// quiz/src/components/Main/Main.vue
<template>
  <div id = "main">
    <Menu @on-selection="select"
          :selected="abaSelecionada"
    ></Menu>
    <Painel :abaAtual="abaSelecionada"> </Painel>
  </div>
</template>

<script setup lang="ts">

import Menu from "../Menu/Menu.vue";
import Painel from "../Painel/Painel.vue";
import {ref} from "vue";

  const abaSelecionada = ref(0)

  function select(optionIndex: number) {
    abaSelecionada.value = optionIndex
  }
</script>

<style scoped>
  #main {
    background-color: aliceblue;
  }
</style>

// quiz/src/components/Main/main.svelte
<div id = "main">
    <Menu on:selection={event => select(event.detail)}
          selected={abaSelecionada}
    ></Menu>
    <Painel abaAtual={abaSelecionada}></Painel>

</div>

<script lang="ts">
    import Menu from '../Menu/menu.svelte'
    import Painel from '../Painel/painel.svelte'

    let abaSelecionada = 0
    function select(optionIndex: number) {
        abaSelecionada = optionIndex
    }
</script>

<style>
    #main {
        background-color: aliceblue;
    }
</style>
